version: "3"

services:
    nginx:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 9000:9000
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - userservice
            - statusservice
            - storyservice

    userservice:
        build: ./userMS
        restart: unless-stopped
        depends_on:
            - userdb

    userdb:
        image: mongo

        ports:
            - 3000:3000

        restart: unless-stopped
        volumes:
            - /mongo:/data/db

    statusservice:
        build: ./statusMS
        restart: unless-stopped
        depends_on:
            - statusdb

    statusdb:
        image: mongo

        ports:
            - 3001:3001

        restart: unless-stopped
        

    storyservice:
        build: ./storyMS
        restart: unless-stopped
        depends_on:
            - storydb
            - storyobjectdb

    storydb:
        image: mongo

        ports:
            - 3002:3002

        restart: unless-stopped
       

    storyobjectdb:
        image: minio/minio:latest
        environment:
            - MINIO_ACCESS_KEY=BmyMIJJcdo6xykFg
            - MINIO_SECRET_KEY=in0Wp2xIMnBIdx8S2RXLxPJMxVdf8VYk
            
        command: server --address 0.0.0.0:9000 /data